const words = {
    // Church Text
    "cross": [ { 
                isThought: true, 
                text: "A wood carving of Jesus is nailed to a cross which is nailed to the wall. Since this church is in space, Jesus is in a space suit, I guess."
                }, { 
                isThought: true, 
                text: "I can never tell what's sacrilegious or not anymore."
                }],
    "casket": [ { isThought: true, text: "Rest in peace, brother." }],
    "priest": [
        { text: "I'm sorry for your loss, Hiruko... Just know that your brother is now at peace." }
    ],
    "oldman": [
        { text: "Your brother was a good man, Hir'ko. I know he'd be proud of the man you are now." },
        { isThought: true, text: "He says that like my brother's been dead for years or something..." }
    ],
    "oldlady": [
        { text: "Masashi was such a good boy... he took such good care of your mother." },
        { text: "Not to say that you don't, of course!" },
        { text: "Oh, I'm sorry, Hiruko. I can't imagine what you're going through right now." },
        { text: "But I should stop rambling, you need to get to the hearse for the funeral procession. In space." }
    ],
    // Space Text
    "intro": [
        { px: 0, py: 0, text: "???: Attention! You are entering protected spacespace. Please reroute immediately.", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: This is a funeral procession. We're heading to the Space Cemetery.", sound: 3 }, 
        { px: 0, py: 0, text: "???: You are FLYING THROUGH A WARZONE!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Oh, geez. Space-oogle Maps didn't tell us there was a war on this route.", sound: 3 }, 
        { px: 0, py: 0, text: "???: Yeah they've really gotten worse at that sort of thing lately I'm not sure what they changed but it's really frustrating sometimes when I--", sound: 0 }, 
        { px: 0, py: 0, text: "???: THAT IS NOT WHAT IS IMPORTANT RIGHT NOW. I am Captain Jonk Stewardeen of the Voynorg Military and you are NOT SAFE HERE. I will escort you to safety, just follow me.", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Alright. Okay, Space-oogle Navigator, please follow that ship.", sound: 3 }, 
        { px: 3, py: 0, text: "Space-oogle Navigator: I'm sorry, I can't find any ships nearby.", sound: 2 },
        { px: 0, py: 0, text: "Stewardeen: Ah, shit. Our cloaking technology is probably hiding us from it. Just switch to manual piloting.", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: I don't know how to drive.", sound: 3 }, 
        { px: 0, py: 0, text: "Stewardeen: ...", sound: 0 }, 
        { px: 0, py: 0, text: "Stewardeen: I...", sound: 0 }, 
        { px: 0, py: 0, text: "Stewardeen: ...", sound: 0 }, 
        { px: 0, py: 0, text: "Stewardeen: Um...", sound: 0 }, 
        { px: 0, py: 0, text: "Stewardeen: ...", sound: 0 }, 
        { px: 0, py: 0, text: "Stewardeen: Okay, so, I really don't have time for this, what with the war and all, so, uh...", sound: 0 }, 
        { px: 0, py: 0, text: "Stewardeen: ...", sound: 0 }, 
        { px: 0, py: 0, text: "Stewardeen: Good luck!", sound: 0 }
    ],
    "firstEncounter": [
        { px: 0, py: 2, text: "???: Oh ho ho! What do we have here? Some new prisoners of war, perhaps?", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Nope!", sound: 3 },
        { px: 0, py: 2, text: "???: Oh, my mistake.", sound: 6 }
    ],
    "secondEncounter": [
        { px: 0, py: 2, text: "???: HEY WAIT A MINUTE! Who are you?! What is your allegiance? Are you friend or foe?", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Buddy I'm just trying to get to the cemetery.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: ...By travelling through a battlefield.", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Yes.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: ...Are you... armed?", options: [{ choice: "Yes", jumpTo: 5 }, { choice: "No", jumpTo: 6 }], sound: 6 },
        { px: 0, py: 2, text: "Buddy: Oh, that's inconvenient. I thought you'd be easy prey or something. Nevermind, see ya!", forceEnd: true, sound: 6 },
        { px: 0, py: 2, text: "Buddy: Interesting! So there's nothing stopping me from attacking you, then.", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: I mean, ethics, maybe?", sound: 3 },
        { px: 0, py: 2, text: "Buddy: Ethics! Bleh! Feh! Look at Mr. Philosophy over here! Patience is a virtue! An eye for an eye makes the whole universe blind! A bird in the hand is worth two in the bush! FEH!", sound: 6 },
        { px: 0, py: 2, text: "Buddy: You think you're better than me because you've got ETHICS?", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Buddy I'm just trying to get to the cemetery.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: Mhm, mhm, I see... well, I don't know about your \"ethics,\" but I do know that time is precious and killing you would be a waste of mine!", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Right. Thanks.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: I'll let you live for now, but unless you want to join whoever you're taking to the cemetery, STAY OUT OF MY WAY!", sound: 6, flag: "honest" }
    ],
    "warzoneWarning": [
        { px: 1, py: 1, text: "???: Hi this is General Jetty Christie, are you aware that you are driving through an active battleground?", sound: 4 },
        { px: 0, py: 1, text: "Hiruko: Yep.", sound: 3 },
        { px: 1, py: 1, text: "Christie: Are you doing that on purpose?", sound: 4 },
        { px: 0, py: 1, text: "Hiruko: Nope. Can't change the autopilot.", sound: 3 },
        { px: 1, py: 1, text: "Christie: Ah, gotcha. Well then, I can try to find somebody who can hack your autopilot to direct you to a safer route.", sound: 4 },
        { px: 0, py: 1, text: "Hiruko: That would be great.", sound: 3 },
        { px: 1, py: 1, text: "Christie: Alright, sit tight, I'll send someone your way soon! Try not to die!", sound: 4 },
        { px: 0, py: 1, text: "Hiruko: Yeah alright.", sound: 3 }
    ],
    "pirate": [
        { px: 2, py: 1, text: "???: AHOY LANDLUBBERS! I BE CAPTAIN SHELBY OF THE SHELBY PIRATES!", sound: 5 },
        { px: 0, py: 1, text: "Hiruko: Cool, hi.", sound: 3 },
        { px: 2, py: 1, text: "Shelby: HAND OVER ALL YER TREASURE AND WE'LL MAYBE GO EASY ON YOU!", sound: 5 },
        { px: 0, py: 1, text: "Hiruko: This is a funeral procession.", sound: 3 },
        { px: 2, py: 1, text: "Shelby: YES! AND A TRUE PIRATE ALWAYS BURIES THEIR TREASURE WITH THEM!", sound: 5 },
        { px: 0, py: 1, text: "Hiruko: That isn't how real life works.", sound: 3 },
        { px: 2, py: 1, text: "Shelby: AND THAT'S WHY I REJECTED REAL LIFE! IT'S A PIRATE'S LIFE FOR ME NOW, SO HAND OVER YOUR TREASURE!", sound: 5,
            options: [
                { choice: "Give nothing.", jumpTo: 7 },
                { choice: "Give bouquet of flowers.", jumpTo: 8 },
                { choice: "Give donation box.", jumpTo: 13 },
                { choice: "Give casket.", jumpTo: 23 },
                { choice: "Give the stand-up comedian that's been with you this whole time.", jumpTo: 26 }
            ] },
        { px: 2, py: 1, text: "Shelby: Still not budging, eh? Well, I'll be back with my entire crew, AND Y'ARR'LL BE SORRY THEN!!", forceEnd: true, sound: 5 }, // 7
        { px: 2, py: 1, text: "Shelby: OH MY GOODNESS THESE ARE LOVELY! ARE THESE WHITE LILIES?", sound: 5 }, // 8
        { px: 0, py: 1, text: "Hiruko: Yes. Because this is a funeral.", sound: 3 },
        { px: 2, py: 1, text: "Shelby: FUNERAL SHMOONERAL! A CORPSE IS A CORPSE OF COURSE, BUT TREASURE IS FOREVER!", sound: 5 },
        { px: 2, py: 1, text: "Shelby: And I'm gonna TREASURE these lilies *sniff* until the DAY I DIE!", sound: 5 },
        { px: 2, py: 1, text: "Shelby: THANKS FOR COOPERATING, LANDLUBBER!", forceEnd: true, sound: 5 },
        { px: 2, py: 1, text: "Shelby: HA-HARRR! A TREASURE CHEST! HOW MUCH GOLD IS THERE IN HERE, I WONDER!", sound: 5 }, // 13
        { px: 0, py: 1, text: "Hiruko: There's like three hundred bucks in there maybe.", sound: 3 },
        { px: 3, py: 1, text: "Shelby: THAT'S... not very much money.", sound: 5 },
        { px: 0, py: 1, text: "Hiruko: Again, this is a funeral procession. I don't know what you were expecting.", sound: 3 },
        { px: 3, py: 1, text: "Shelby: ...", sound: 5 },
        { px: 3, py: 1, text: "Shelby: This is sort of depressing, actually.", sound: 5 },
        { px: 0, py: 1, text: "Hiruko: Yeah, you think?", sound: 3 },
        { px: 3, py: 1, text: "Shelby: Yeah, I'm gonna... go pillage someone else now. I'm, uh, sorry for your loss.", sound: 5 },
        { px: 0, py: 1, text: "Hiruko: Can I have that money back--", sound: 3 },
        { px: 2, py: 1, text: "Shelby: SHELBY'S PIRATES... AWAYYY!!!!", forceEnd: true, sound: 5 },
        { px: 3, py: 1, text: "Shelby: What the fuck are you trying to GIVE THE CORPSE TO ME?", sound: 5 }, // 23
        { px: 0, py: 1, text: "Hiruko: It's all we have.", sound: 3 },
        { px: 3, py: 1, text: "Shelby: I'm not comfortable with this. Keep your dead guy. I'm gonna go loot someone else!", forceEnd: true, sound: 5 },
        { px: 0, py: 1, text: "Hiruko: You can have this guy, I guess.", sound: 3 },
        { px: 1, py: 2, text: "Donkle: What's the deal with space pirates? We're in a POST-SCARCITY ECONOMY, FOLKS! We don't NEED to steal anymore!", sound: 7 },
        { px: 3, py: 1, text: "Shelby: THAT WASN'T EVEN A JOKE! THAT WAS JUST AN OBSERVATION!", sound: 5 },
        { px: 1, py: 2, text: "Donkle: No, it was an observational COMEDY!", sound: 7 },
        { px: 3, py: 1, text: "Shelby: NO, IT WAS *JUST* AN OBSERVATION! THERE NEEDS TO BE SOMETHING FUNNY ABOUT IT FOR IT TO BE OBSERVATIONAL COMEDY!", sound: 5 },
        { px: 1, py: 2, text: "Donkle: You don't think that's funny? You can do anything you want, nothing is holding you back, and you're still robbing people!", sound: 7 },
        { px: 2, py: 1, text: "Shelby: MAYBE ROBBING PEOPLE IS WHAT I WANT TO DO!", sound: 5 },
        { px: 1, py: 2, text: "Donkle: More than anything? Even more than... crochet?", sound: 7 },
        { px: 2, py: 2, text: "[laugh track]", sound: 7 },
        { px: 3, py: 1, text: "Shelby: WAS THAT SUPPOSED TO BE A JOKE?", sound: 5 },
        { px: 1, py: 2, text: "Donkle: See, it was funny because crochet is also something that people would be unlikely to want to do.", sound: 7 },
        { px: 0, py: 1, text: "Hiruko: I like crocheting.", sound: 3 },
        { px: 2, py: 1, text: "Shelby: YEAH, I DO, TOO. CROCHETING IS GREAT, WHAT'S YOUR PROBLEM?", sound: 5 },
        { px: 1, py: 2, text: "Donkle: I don't like hobbies that aren't traditionally masculine.", sound: 7 },
        { px: 2, py: 1, text: "Shelby: YOU NEED TO GET OUT MORE.", sound: 5 },
        { px: 1, py: 2, text: "Donkle: No I don't! What would I, an observational comedian, benefit from experiencing more things??", sound: 7 },
        { px: 3, py: 1, text: "Shelby: OKAY, THAT WAS A JOKE, RIGHT?", sound: 5 },
        { px: 1, py: 2, text: "Donkle: No it wasn't! I'm going to write a new routine about how the younger generations just DON'T UNDERSTAND!", sound: 7 },
        { px: 3, py: 1, text: "Shelby: OKAY HAVE FUN WITH THAT. I'M GONNA GO ROB SOMEONE ELSE NOW.", sound: 5 },
        { px: 0, py: 1, text: "Hiruko: No. Wait. Please take him.", sound: 3 },
        { px: 2, py: 2, text: "Donkle: Sorry, pal, but that ship sailed long ago! Heh, that one was almost funny!", sound: 7, flag: "joker" }
    ],
    "attacker": [
        { px: 3, py: 2, text: "???: Attention! You're in Skunglr territory! Turn back immediately or be destroyed!", sound: 8 },
        { px: 0, py: 1, text: "Hiruko: Can't. Autopilot won't let me change it.", sound: 3 },
        { px: 3, py: 2, text: "???: Then say your prayers.", sound: 8 },
        { px: 0, py: 1, text: "Hiruko: Been doing that a lot today.", sound: 3 }
    ],
    "return": [
        { px: 0, py: 0, text: "Stewardeen: Wow, you're still alive! Good thing we were here to stop that Skunglr Attack Ship, eh?", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Yeah, thanks. Also, what are Skunglrs?", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: They're an alien race hellbent on destroying all of mankind!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Why?", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: They're a shoot-first-ask-questions-later species, so we've never asked!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Maybe you should do that.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: We're a shoot-first-ask-questions-later species, so there's no time for that!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Cool, great.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: Anyway, we're off to do some more war things. Try to stay out of trouble!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Easier said than done in a warzone.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: Ha ha, good one!", sound: 0 }
    ],
    "joaje": [
        { px: 1, py: 2, text: "Donkle: Hey, so I've been working on my new routine. Wanna hear?", sound: 7 },
        { px: 0, py: 1, text: "Hiruko: No.", sound: 3 },
        { px: 1, py: 2, text: "Donkle: Great! So: I ran into a pirate the other day. I know, right? A pirate? These days? Like, get a real job, right? Like crochet!", sound: 7 },
        { px: 0, py: 1, text: "Hiruko: This sounds familiar and also isn't actually funny.", sound: 3 },
        { px: 1, py: 2, text: "Donkle: I'm GETTING to the funny part! Anyway, this pirate is like \"arr hand over yer treasure\" and all that, but I don't HAVE any treasure!", sound: 7 },
        { px: 1, py: 2, text: "Donkle: But the pirate wants treasure! Pirates, am I right? They're always after one thing: booty!", sound: 7 },
        { px: 0, py: 1, text: "Hiruko: Please stop.", sound: 3 },
        { px: 2, py: 2, text: "Donkle: Booty!", sound: 7 }
    ],
    "hacker": [
        { px: 1, py: 0, text: "???: Hi! I'm here to help you with your autopilot.", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: Great. What do you need me to do?", sound: 3 },
        { px: 1, py: 0, text: "???: Let's see... your vehicle looks like a somewhat recent model... do you see a control panel with six red buttons on it?", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: Hmm. Yeah, there's one of those with two rows of three buttons.", sound: 3 },
        { px: 1, py: 0, text: "???: Perfect! Press the middle button on the top, then the bottom right one!", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: Alright.", sound: 3 },
        { px: 0, py: 1, text: "[click, click]", trigger: 1 },
        { px: 0, py: 1, text: "Hiruko: Uh, looks like the car stopped.", sound: 3 },
        { px: 1, py: 0, text: "???: Yes... and your shields are off, too!", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: That sounds like not a good thing to have done, then.", sound: 3 },
        { px: 1, py: 0, text: "???: Not good for you, maybe...", sound: 1 },
        { px: 2, py: 0, text: "???: But VERY good for me!", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: Your dramatic betrayal would matter a lot more if I had known you for more than 5 minutes.", sound: 3 },
        { px: 2, py: 0, text: "???: Shut up! You know damn well who I am!", sound: 1 },
        { px: 2, py: 0, text: "???: I'm the mole hired by the Skunglrs to find the secret spy the Voynorg have been working with!", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: Okay.", sound: 3 },
        { px: 2, py: 0, text: "???: And after doing my research, I have determined that their spy... is YOU!", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: No it isn't.", sound: 3 },
        { px: 2, py: 0, text: "???: It was pretty clever of you, pretending to be a funeral procession!", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: No it wasn't.", sound: 3 },
        { px: 2, py: 0, text: "???: But I'm no fool! No one would willingly drive through a warzone if they didn't have to!", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: I can assure you that we are not willingly doing this.", sound: 3 },
        { px: 2, py: 0, text: "???: A likely story... but THE SKUNGLR ARMY WILL DEFEAT THE VOYNORGS!", sound: 1 }
    ],
    "usfound": [
        { px: 0, py: 0, text: "Stewardeen: Scrag! What are you doing? That's a civilian you're attacking!", sound: 0 },
        { px: 2, py: 0, text: "Scrag: No, that's a GOOD-FOR-NOTHING Voynorg I'm attacking!", sound: 1 },
        { px: 0, py: 0, text: "Stewardeen: Scrag, WE'RE the Voynorgs.", sound: 0 },
        { px: 2, py: 0, text: "Scrag: WE'RE nothing! I'm working for the Skunglrs!", sound: 1 },
        { px: 0, py: 0, text: "Stewardeen: Gasp! You were a mole! I've known you for approximately 6 minutes and this dramatic betrayal is a huge surprise to me!", sound: 0 },
        { px: 2, py: 0, text: "Scrag: Isn't it??! Nyehehehe! You Voynorgs are fools for crossing the Skunglrs!", sound: 1 },
        { px: 0, py: 0, text: "Stewardeen: But why, Scrag? Why would you betray your own people?! Do the Skunglrs fight for a cause more noble than ours?", sound: 0 },
        { px: 2, py: 0, text: "Scrag: Who cares about nobleness? The Skunglrs made me an offer I couldn't refuse!", sound: 1 },
        { px: 0, py: 0, text: "Stewardeen: How much did they offer you? A million space dollars? Two million??", sound: 0 },
        { px: 2, py: 0, text: "Scrag: Even better! THREE whole bit-spacecoins!", sound: 1 },
        { px: 0, py: 0, text: "Stewardeen: ...Scrag those are worthless.", sound: 0 },
        { px: 2, py: 0, text: "Scrag: THEY WERE WORTH A LOT WHEN I ACCEPTED THEM SHUT THE FUCK UP!", sound: 1 },
        { px: 0, py: 0, text: "Stewardeen: Either way, this ends now, Scrag. You're coming with me.", sound: 0 },
        { px: 2, py: 0, text: "Scrag: YOU'LL NEVER TAKE ME ALIVE, STEWARDEEN!", sound: 1 },
        { px: 0, py: 0, text: "Stewardeen: Okay.", sound: 0 },
        { px: 2, py: 0, text: "Scrag: wait no SHIT", sound: 1 }
    ],
    "stewardeenSaved": [
        { px: 0, py: 0, text: "Stewardeen: I'm very sorry about that, on behalf of the entire Voynorg Military.", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Okay. Can you tell me how to fix my car?", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: But of course! Just press the same buttons again!", sound: 0 },
        { px: 0, py: 1, text: "[click, click]", trigger: 2 },
        { px: 0, py: 1, text: "Hiruko: Cool I should have tried that sooner.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: The cemetery is close now, I'll escort you the rest of the way!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Great thanks.", sound: 3 }
    ],
    "stewardeenEnd": [
        { px: 0, py: 0, text: "Stewardeen: There it is! The Space Cemetery!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: I wonder how long it'll take before people stop naming things by just putting the word \"Space\" in front of them.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: Why, that's the best idea since Canned Space Bread!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Great. Thanks.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: This certainly has been an unforgettable experience, hasn't it? Ha ha!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: This is literally my brother's funeral.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: Ha ha... Right... Well, I think we all still learned a valuable lesson today!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Did we?", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: Yes! It's bad to lie! Scrag lied about his allegiances and now he's dead!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Sure I guess that's a moral.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: Have you lied to anyone recently? If not, you should start this game over and try not doing that!", sound: 0 },
        { px: 0, py: 1, text: "Hiruko: Oh good multiple endings. That's video games, alright.", sound: 3 },
        { px: 0, py: 0, text: "Stewardeen: Ha ha... It sure is! Anyway, have fun at the cemete--... I'm just gonna stop saying things.", sound: 0 }
    ],
    "alienfound": [
        { px: 0, py: 2, text: "Buddy: ETHICS!!", sound: 6 },
        { px: 2, py: 0, text: "???: What?", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: What?", sound: 3 },
        { px: 0, py: 2, text: "Buddy: I been doing some reading... since I saw you last, funeral humans.", sound: 6 },
        { px: 2, py: 0, text: "???: You know them?", sound: 1 },
        { px: 0, py: 2, text: "Buddy: Oh yeah, we go way back. Like, 10 minutes ago at least.", sound: 6 },
        { px: 2, py: 0, text: "???: Well, I'm about to kill them for our emperor, so if you could just... move to the side so I can...", sound: 1 },
        { px: 0, py: 2, text: "Buddy: ETHICS!!", sound: 6 },
        { px: 2, py: 0, text: "???: WHY DO YOU KEEP YELLING THAT?!", sound: 1 },
        { px: 0, py: 2, text: "Buddy: Do you know WHY we fight, Scrag?", sound: 6 },
        { px: 2, py: 0, text: "Scrag: I fight because your leader paid me in cryptocurrency to betray my fellow man.", sound: 1 },
        { px: 0, py: 2, text: "Buddy: Betrayal! What a human trait! Perhaps the most pathetic of all of them!", sound: 6 },
        { px: 2, py: 0, text: "Scrag: What are you talking about?", sound: 1 },
        { px: 0, py: 2, text: "Buddy: I've been reading about what it means to be a conscious and/or sentient being. You humans have written some good stuff.", sound: 6 },
        { px: 2, py: 0, text: "Scrag: I don't care, please let me kill these harmless civilians.", sound: 1 },
        { px: 0, py: 2, text: "Buddy: MANY CREATURES FIGHT AND KILL FOR SURVIVAL... but only humans... kill for money.", sound: 6 },
        { px: 2, py: 0, text: "Scrag: Hey sometimes we do it to impress women.", sound: 1 },
        { px: 0, py: 2, text: "Buddy: SILENCE, OR I SHALL ASK MY FRIENDS IF THEIR HEARSE HAS ROOM FOR ONE MORE CORPSE.", sound: 6 },
        { px: 2, py: 0, text: "Scrag: Gulp!", sound: 1 },
        { px: 0, py: 1, text: "Hiruko: (It doesn't)", sound: 3 },
        { px: 0, py: 2, text: "Buddy: Do you know WHY the Skunglr fight the Voynorgs, Scrag?", sound: 6 },
        { px: 2, py: 0, text: "Scrag: N-no...", sound: 1 },
        { px: 0, py: 2, text: "Buddy: The humans have attempted to colonize planets in our solar system, greatly affecting the galaxy's ecosystem!", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Yeah, that sounds about right.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: And why do you think the Voynorgs fight the Skunglr?", sound: 6 },
        { px: 2, py: 0, text: "Scrag: I suspect that the answer to this will make me sound like the bad guy here.", sound: 1 },
        { px: 0, py: 2, text: "Buddy: YOU ARE THE BAD GUY HERE! The Voynorgs want to mine our planets of precious ores for money! FOR MONEY!", sound: 6 },
        { px: 2, py: 0, text: "Scrag: I mean, money is nice so--", sound: 1 },
        { px: 0, py: 2, text: "Buddy: EVERYONE IN THE UNIVERSE ALREADY HAS ACCESS TO FREE FOOD, SHELTER, AND HEALTHCARE, SCRAG! MONEY IS JUST A LUXURY NOW!!", sound: 6 },
        { px: 2, py: 0, text: "Scrag: ...I mean, luxuries are nice so--", sound: 1 },
        { px: 0, py: 2, text: "Buddy: I DIDN'T ASK FOR YOU TO SAY WORDS.", sound: 6 },
        { px: 2, py: 0, text: "Scrag: Gulp!", sound: 1 },
        { px: 0, py: 2, text: "Buddy: But... not all humans are evil. I read the works of many great human philosophers after I last spoke with the funeral humans.", sound: 6 },
        { px: 0, py: 2, text: "Buddy: The human mind is capable of great evil, but also great kindness.", sound: 6 },
        { px: 0, py: 2, text: "Buddy: By not lying to me, this funeral human showed me that some humans are dedicated to making the universe a better place for everyone.", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: All I did was say that I my car wasn't armed.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: Yeah well that's just because we didn't have time for you to make any actually meaningful choices; this game was made in like a day, you know!", sound: 6 },
        { px: 2, py: 0, text: "Scrag: We're in a game?!", sound: 1 },
        { px: 0, py: 2, text: "Buddy: STOP SAYING WORDS!", sound: 6 },
    ],
    "alienSaved": [
        { px: 0, py: 2, text: "Buddy: ETHICS!!", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Sure okay.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: There are a lot of humans out there who want to cause harm. One less of them now, I guess, but still.", sound: 6 },
        { px: 0, py: 2, text: "Buddy: I now know that not all humans are evil. Some are good, and I think you're one of them.", sound: 6 },
        { px: 0, py: 2, text: "Buddy: But BEING good is not enough, my friend, you must DO good as well!", sound: 6 },
        { px: 0, py: 2, text: "Buddy: At the end of the day, it is not THOUGHTS that change the world, but ACTIONS!", sound: 6 },
        { px: 0, py: 2, text: "Buddy: If you just let your heart guide your actions, you'll be able to change the world... and the galaxy... and even the universe!", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Cool can I go bury my dead brother now?", sound: 3 },
        { px: 0, py: 2, text: "Buddy: Oh, right. Humans mourn the loss of family members. Sorry.", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: It's alright. You saved my life so I guess letting you monologue is the least I can do to repay you.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: If you want to repay me, do your part to make the world a better place!", sound: 6 },
        { px: 0, py: 2, text: "Buddy: And that goes for you, too, person playing this game! Especially since you'll continue to exist after this game ends!", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: I can hear you, you know.", sound: 3 },
        { px: 0, py: 2, text: "Buddy: Then hear this, friend! We're going to that cemetery to bury your brother, have a solemn moment of silence, and then the game ends!", sound: 6 },
        { px: 0, py: 1, text: "Hiruko: Sounds great.", trigger: 2, sound: 3 }
    ],
    "gameover": [
        { px: 0, py: 1, text: "Hiruko: Well that's bad.", sound: 3 }
    ]
};